--------------------------------------------------------
--  File created - Wednesday-October-10-2018   
--------------------------------------------------------
Insert into COUNTRY_CODES (COC_AUTO_KEY,CODE,COUNTRY_NAME,SDF_COC_002,SDF_COC_003) values (1,'LT','Lithuania','Europe','T');
Insert into COUNTRY_CODES (COC_AUTO_KEY,CODE,COUNTRY_NAME,SDF_COC_002,SDF_COC_003) values (229,'KR','Republic of South Korea','Asia','F');
Insert into COUNTRY_CODES (COC_AUTO_KEY,CODE,COUNTRY_NAME,SDF_COC_002,SDF_COC_003) values (224,'PL','Poland','Europe','T');
Insert into COUNTRY_CODES (COC_AUTO_KEY,CODE,COUNTRY_NAME,SDF_COC_002,SDF_COC_003) values (5,'DE','Germany','Europe','T');
Insert into COUNTRY_CODES (COC_AUTO_KEY,CODE,COUNTRY_NAME,SDF_COC_002,SDF_COC_003) values (223,'RS','Serbia','Europe','F');
Insert into COUNTRY_CODES (COC_AUTO_KEY,CODE,COUNTRY_NAME,SDF_COC_002,SDF_COC_003) values (3,'US','USA','North America','F');
Insert into COUNTRY_CODES (COC_AUTO_KEY,CODE,COUNTRY_NAME,SDF_COC_002,SDF_COC_003) values (6,'AD','Andorra','Europe','F');
Insert into COUNTRY_CODES (COC_AUTO_KEY,CODE,COUNTRY_NAME,SDF_COC_002,SDF_COC_003) values (7,'AE','United Arab Emirates','Asia','F');
Insert into COUNTRY_CODES (COC_AUTO_KEY,CODE,COUNTRY_NAME,SDF_COC_002,SDF_COC_003) values (8,'AF','Afghanistan','Asia','F');
Insert into COUNTRY_CODES (COC_AUTO_KEY,CODE,COUNTRY_NAME,SDF_COC_002,SDF_COC_003) values (9,'AG','Antigua and Barbuda','Central America','F');
Insert into COUNTRY_CODES (COC_AUTO_KEY,CODE,COUNTRY_NAME,SDF_COC_002,SDF_COC_003) values (10,'AI','Anguilla','North America','F');
Insert into COUNTRY_CODES (COC_AUTO_KEY,CODE,COUNTRY_NAME,SDF_COC_002,SDF_COC_003) values (11,'AL','Albania','Europe','F');
Insert into COUNTRY_CODES (COC_AUTO_KEY,CODE,COUNTRY_NAME,SDF_COC_002,SDF_COC_003) values (12,'AM','Armenia','Asia','F');
Insert into COUNTRY_CODES (COC_AUTO_KEY,CODE,COUNTRY_NAME,SDF_COC_002,SDF_COC_003) values (13,'AN','Netherlands Antilles','North America','F');
Insert into COUNTRY_CODES (COC_AUTO_KEY,CODE,COUNTRY_NAME,SDF_COC_002,SDF_COC_003) values (14,'AR','Argentina','South America','F');
Insert into COUNTRY_CODES (COC_AUTO_KEY,CODE,COUNTRY_NAME,SDF_COC_002,SDF_COC_003) values (15,'AS','American Samoa','Australia/Oceania','F');
Insert into COUNTRY_CODES (COC_AUTO_KEY,CODE,COUNTRY_NAME,SDF_COC_002,SDF_COC_003) values (16,'AT','Austria','Europe','T');
Insert into COUNTRY_CODES (COC_AUTO_KEY,CODE,COUNTRY_NAME,SDF_COC_002,SDF_COC_003) values (17,'ZW','Zimbabwe','Africa','F');
Insert into COUNTRY_CODES (COC_AUTO_KEY,CODE,COUNTRY_NAME,SDF_COC_002,SDF_COC_003) values (18,'ZR','Zaire','Africa','F');
Insert into COUNTRY_CODES (COC_AUTO_KEY,CODE,COUNTRY_NAME,SDF_COC_002,SDF_COC_003) values (19,'ZM','Zambia','Africa','F');
Insert into COUNTRY_CODES (COC_AUTO_KEY,CODE,COUNTRY_NAME,SDF_COC_002,SDF_COC_003) values (20,'ZA','South Africa','Africa','F');
Insert into COUNTRY_CODES (COC_AUTO_KEY,CODE,COUNTRY_NAME,SDF_COC_002,SDF_COC_003) values (21,'YU','Yugoslavia','Europe','F');
Insert into COUNTRY_CODES (COC_AUTO_KEY,CODE,COUNTRY_NAME,SDF_COC_002,SDF_COC_003) values (22,'YE','Yemen','Asia','F');
Insert into COUNTRY_CODES (COC_AUTO_KEY,CODE,COUNTRY_NAME,SDF_COC_002,SDF_COC_003) values (23,'WS','Samoa','Australia/Oceania','F');
Insert into COUNTRY_CODES (COC_AUTO_KEY,CODE,COUNTRY_NAME,SDF_COC_002,SDF_COC_003) values (24,'WF','Wallis and Futuna Islands','Australia/Oceania','F');
Insert into COUNTRY_CODES (COC_AUTO_KEY,CODE,COUNTRY_NAME,SDF_COC_002,SDF_COC_003) values (25,'VU','Vanuatu','Australia/Oceania','F');
Insert into COUNTRY_CODES (COC_AUTO_KEY,CODE,COUNTRY_NAME,SDF_COC_002,SDF_COC_003) values (26,'VN','Vietnam','Asia','F');
Insert into COUNTRY_CODES (COC_AUTO_KEY,CODE,COUNTRY_NAME,SDF_COC_002,SDF_COC_003) values (27,'VI','Virgin Islands (USA)','North America','F');
Insert into COUNTRY_CODES (COC_AUTO_KEY,CODE,COUNTRY_NAME,SDF_COC_002,SDF_COC_003) values (28,'VG','Virgin Islands (British)','North America','F');
Insert into COUNTRY_CODES (COC_AUTO_KEY,CODE,COUNTRY_NAME,SDF_COC_002,SDF_COC_003) values (29,'VE','Venezuela','South America','F');
Insert into COUNTRY_CODES (COC_AUTO_KEY,CODE,COUNTRY_NAME,SDF_COC_002,SDF_COC_003) values (30,'VC','Saint Vincent & Grenadines','Central America','F');
Insert into COUNTRY_CODES (COC_AUTO_KEY,CODE,COUNTRY_NAME,SDF_COC_002,SDF_COC_003) values (31,'UZ','Uzbekistan','Asia','F');
Insert into COUNTRY_CODES (COC_AUTO_KEY,CODE,COUNTRY_NAME,SDF_COC_002,SDF_COC_003) values (32,'UY','Uruguay','South America','F');
Insert into COUNTRY_CODES (COC_AUTO_KEY,CODE,COUNTRY_NAME,SDF_COC_002,SDF_COC_003) values (36,'UG','Uganda','Africa','F');
Insert into COUNTRY_CODES (COC_AUTO_KEY,CODE,COUNTRY_NAME,SDF_COC_002,SDF_COC_003) values (34,'UM','USA Minor Outlying Islands','North America','F');
Insert into COUNTRY_CODES (COC_AUTO_KEY,CODE,COUNTRY_NAME,SDF_COC_002,SDF_COC_003) values (35,'UK','United Kingdom','Europe','T');
Insert into COUNTRY_CODES (COC_AUTO_KEY,CODE,COUNTRY_NAME,SDF_COC_002,SDF_COC_003) values (37,'UA','Ukraine','Europe','F');
Insert into COUNTRY_CODES (COC_AUTO_KEY,CODE,COUNTRY_NAME,SDF_COC_002,SDF_COC_003) values (38,'TZ','Tanzania','Africa','F');
Insert into COUNTRY_CODES (COC_AUTO_KEY,CODE,COUNTRY_NAME,SDF_COC_002,SDF_COC_003) values (39,'TW','Taiwan','Asia','F');
Insert into COUNTRY_CODES (COC_AUTO_KEY,CODE,COUNTRY_NAME,SDF_COC_002,SDF_COC_003) values (40,'TV','Tuvalu','Australia/Oceania','F');
Insert into COUNTRY_CODES (COC_AUTO_KEY,CODE,COUNTRY_NAME,SDF_COC_002,SDF_COC_003) values (41,'TT','Trinidad and Tobago','Central America','F');
Insert into COUNTRY_CODES (COC_AUTO_KEY,CODE,COUNTRY_NAME,SDF_COC_002,SDF_COC_003) values (42,'TR','Turkey','Asia','F');
Insert into COUNTRY_CODES (COC_AUTO_KEY,CODE,COUNTRY_NAME,SDF_COC_002,SDF_COC_003) values (43,'TO','Tonga','Australia/Oceania','F');
Insert into COUNTRY_CODES (COC_AUTO_KEY,CODE,COUNTRY_NAME,SDF_COC_002,SDF_COC_003) values (44,'TN','Tunisia','Africa','F');
Insert into COUNTRY_CODES (COC_AUTO_KEY,CODE,COUNTRY_NAME,SDF_COC_002,SDF_COC_003) values (45,'TM','Turkmenistan','Asia','F');
Insert into COUNTRY_CODES (COC_AUTO_KEY,CODE,COUNTRY_NAME,SDF_COC_002,SDF_COC_003) values (46,'TK','Tokelau','Australia/Oceania','F');
Insert into COUNTRY_CODES (COC_AUTO_KEY,CODE,COUNTRY_NAME,SDF_COC_002,SDF_COC_003) values (47,'TJ','Tajikistan','Asia','F');
Insert into COUNTRY_CODES (COC_AUTO_KEY,CODE,COUNTRY_NAME,SDF_COC_002,SDF_COC_003) values (48,'TH','Thailand','Asia','F');
Insert into COUNTRY_CODES (COC_AUTO_KEY,CODE,COUNTRY_NAME,SDF_COC_002,SDF_COC_003) values (49,'TG','Togo','Africa','F');
Insert into COUNTRY_CODES (COC_AUTO_KEY,CODE,COUNTRY_NAME,SDF_COC_002,SDF_COC_003) values (50,'TF','French Southern Territories','Antarctica','F');
Insert into COUNTRY_CODES (COC_AUTO_KEY,CODE,COUNTRY_NAME,SDF_COC_002,SDF_COC_003) values (51,'TD','Chad','Africa','F');
Insert into COUNTRY_CODES (COC_AUTO_KEY,CODE,COUNTRY_NAME,SDF_COC_002,SDF_COC_003) values (52,'TC','Turks and Caicos Islands','Central America','F');
Insert into COUNTRY_CODES (COC_AUTO_KEY,CODE,COUNTRY_NAME,SDF_COC_002,SDF_COC_003) values (53,'SZ','Swaziland','Africa','F');
Insert into COUNTRY_CODES (COC_AUTO_KEY,CODE,COUNTRY_NAME,SDF_COC_002,SDF_COC_003) values (54,'SY','Syria','Asia','F');
Insert into COUNTRY_CODES (COC_AUTO_KEY,CODE,COUNTRY_NAME,SDF_COC_002,SDF_COC_003) values (55,'SR','Suriname','South America','F');
Insert into COUNTRY_CODES (COC_AUTO_KEY,CODE,COUNTRY_NAME,SDF_COC_002,SDF_COC_003) values (56,'SO','Somalia','Africa','F');
Insert into COUNTRY_CODES (COC_AUTO_KEY,CODE,COUNTRY_NAME,SDF_COC_002,SDF_COC_003) values (57,'SN','Senegal','Africa','F');
Insert into COUNTRY_CODES (COC_AUTO_KEY,CODE,COUNTRY_NAME,SDF_COC_002,SDF_COC_003) values (58,'SM','San Marino','Europe','F');
Insert into COUNTRY_CODES (COC_AUTO_KEY,CODE,COUNTRY_NAME,SDF_COC_002,SDF_COC_003) values (59,'SL','Sierra Leone','Africa','F');
Insert into COUNTRY_CODES (COC_AUTO_KEY,CODE,COUNTRY_NAME,SDF_COC_002,SDF_COC_003) values (60,'SK','Slovakia','Europe','T');
Insert into COUNTRY_CODES (COC_AUTO_KEY,CODE,COUNTRY_NAME,SDF_COC_002,SDF_COC_003) values (61,'SJ','Svalbard and Jan Mayen Islands','Europe','F');
Insert into COUNTRY_CODES (COC_AUTO_KEY,CODE,COUNTRY_NAME,SDF_COC_002,SDF_COC_003) values (62,'SI','Slovenia','Europe','T');
Insert into COUNTRY_CODES (COC_AUTO_KEY,CODE,COUNTRY_NAME,SDF_COC_002,SDF_COC_003) values (63,'SH','Saint Helena','Africa','F');
Insert into COUNTRY_CODES (COC_AUTO_KEY,CODE,COUNTRY_NAME,SDF_COC_002,SDF_COC_003) values (64,'SG','Singapore','Asia','F');
Insert into COUNTRY_CODES (COC_AUTO_KEY,CODE,COUNTRY_NAME,SDF_COC_002,SDF_COC_003) values (65,'SE','Sweden','Europe','T');
Insert into COUNTRY_CODES (COC_AUTO_KEY,CODE,COUNTRY_NAME,SDF_COC_002,SDF_COC_003) values (66,'SC','Seychelles','Africa','F');
Insert into COUNTRY_CODES (COC_AUTO_KEY,CODE,COUNTRY_NAME,SDF_COC_002,SDF_COC_003) values (67,'SB','Solomon Islands','Australia/Oceania','F');
Insert into COUNTRY_CODES (COC_AUTO_KEY,CODE,COUNTRY_NAME,SDF_COC_002,SDF_COC_003) values (68,'SA','Saudi Arabia','Asia','F');
Insert into COUNTRY_CODES (COC_AUTO_KEY,CODE,COUNTRY_NAME,SDF_COC_002,SDF_COC_003) values (69,'RW','Rwanda','Africa','F');
Insert into COUNTRY_CODES (COC_AUTO_KEY,CODE,COUNTRY_NAME,SDF_COC_002,SDF_COC_003) values (70,'RU','Russian Federation','Europe','F');
Insert into COUNTRY_CODES (COC_AUTO_KEY,CODE,COUNTRY_NAME,SDF_COC_002,SDF_COC_003) values (71,'RO','Romania','Europe','T');
Insert into COUNTRY_CODES (COC_AUTO_KEY,CODE,COUNTRY_NAME,SDF_COC_002,SDF_COC_003) values (72,'RE','Reunion (French)','Africa','F');
Insert into COUNTRY_CODES (COC_AUTO_KEY,CODE,COUNTRY_NAME,SDF_COC_002,SDF_COC_003) values (73,'QA','Qatar','Asia','F');
Insert into COUNTRY_CODES (COC_AUTO_KEY,CODE,COUNTRY_NAME,SDF_COC_002,SDF_COC_003) values (74,'PW','Palau','Australia/Oceania','F');
Insert into COUNTRY_CODES (COC_AUTO_KEY,CODE,COUNTRY_NAME,SDF_COC_002,SDF_COC_003) values (75,'PT','Portugal','Europe','T');
Insert into COUNTRY_CODES (COC_AUTO_KEY,CODE,COUNTRY_NAME,SDF_COC_002,SDF_COC_003) values (76,'PR','Puerto Rico','Central America','F');
Insert into COUNTRY_CODES (COC_AUTO_KEY,CODE,COUNTRY_NAME,SDF_COC_002,SDF_COC_003) values (77,'PN','Pitcairn Island','Australia/Oceania','F');
Insert into COUNTRY_CODES (COC_AUTO_KEY,CODE,COUNTRY_NAME,SDF_COC_002,SDF_COC_003) values (78,'PM','Saint Pierre and Miquelon','North America','F');
Insert into COUNTRY_CODES (COC_AUTO_KEY,CODE,COUNTRY_NAME,SDF_COC_002,SDF_COC_003) values (79,'PK','Pakistan','Asia','F');
Insert into COUNTRY_CODES (COC_AUTO_KEY,CODE,COUNTRY_NAME,SDF_COC_002,SDF_COC_003) values (80,'PH','Philippines','Asia','F');
Insert into COUNTRY_CODES (COC_AUTO_KEY,CODE,COUNTRY_NAME,SDF_COC_002,SDF_COC_003) values (81,'PG','Papua New Guinea','Australia/Oceania','F');
Insert into COUNTRY_CODES (COC_AUTO_KEY,CODE,COUNTRY_NAME,SDF_COC_002,SDF_COC_003) values (82,'PE','Peru','South America','F');
Insert into COUNTRY_CODES (COC_AUTO_KEY,CODE,COUNTRY_NAME,SDF_COC_002,SDF_COC_003) values (83,'PA','Panama','Central America','F');
Insert into COUNTRY_CODES (COC_AUTO_KEY,CODE,COUNTRY_NAME,SDF_COC_002,SDF_COC_003) values (84,'AU','Australia','Australia/Oceania','F');
Insert into COUNTRY_CODES (COC_AUTO_KEY,CODE,COUNTRY_NAME,SDF_COC_002,SDF_COC_003) values (85,'AW','Aruba','South America','F');
Insert into COUNTRY_CODES (COC_AUTO_KEY,CODE,COUNTRY_NAME,SDF_COC_002,SDF_COC_003) values (86,'AZ','Azerbaijan','Asia','F');
Insert into COUNTRY_CODES (COC_AUTO_KEY,CODE,COUNTRY_NAME,SDF_COC_002,SDF_COC_003) values (87,'BB','Barbados','Central America','F');
Insert into COUNTRY_CODES (COC_AUTO_KEY,CODE,COUNTRY_NAME,SDF_COC_002,SDF_COC_003) values (88,'BD','Bangladesh','Asia','F');
Insert into COUNTRY_CODES (COC_AUTO_KEY,CODE,COUNTRY_NAME,SDF_COC_002,SDF_COC_003) values (89,'BE','Belgium','Europe','T');
Insert into COUNTRY_CODES (COC_AUTO_KEY,CODE,COUNTRY_NAME,SDF_COC_002,SDF_COC_003) values (90,'BF','Burkina Faso','Africa','F');
Insert into COUNTRY_CODES (COC_AUTO_KEY,CODE,COUNTRY_NAME,SDF_COC_002,SDF_COC_003) values (91,'BG','Bulgaria','Europe','T');
Insert into COUNTRY_CODES (COC_AUTO_KEY,CODE,COUNTRY_NAME,SDF_COC_002,SDF_COC_003) values (92,'BH','Bahrain','Asia','F');
Insert into COUNTRY_CODES (COC_AUTO_KEY,CODE,COUNTRY_NAME,SDF_COC_002,SDF_COC_003) values (94,'BN','Brunei Darussalam','Asia','F');
Insert into COUNTRY_CODES (COC_AUTO_KEY,CODE,COUNTRY_NAME,SDF_COC_002,SDF_COC_003) values (95,'BR','Brazil','South America','F');
Insert into COUNTRY_CODES (COC_AUTO_KEY,CODE,COUNTRY_NAME,SDF_COC_002,SDF_COC_003) values (96,'BS','Bahamas','Central America','F');
Insert into COUNTRY_CODES (COC_AUTO_KEY,CODE,COUNTRY_NAME,SDF_COC_002,SDF_COC_003) values (97,'BT','Bhutan','Asia','F');
Insert into COUNTRY_CODES (COC_AUTO_KEY,CODE,COUNTRY_NAME,SDF_COC_002,SDF_COC_003) values (98,'BV','Bouvet Island','Antarctica','F');
Insert into COUNTRY_CODES (COC_AUTO_KEY,CODE,COUNTRY_NAME,SDF_COC_002,SDF_COC_003) values (99,'BW','Botswana','Africa','F');
Insert into COUNTRY_CODES (COC_AUTO_KEY,CODE,COUNTRY_NAME,SDF_COC_002,SDF_COC_003) values (100,'BY','Belarus','Europe','F');
Insert into COUNTRY_CODES (COC_AUTO_KEY,CODE,COUNTRY_NAME,SDF_COC_002,SDF_COC_003) values (101,'BZ','Belize','Central America','F');
Insert into COUNTRY_CODES (COC_AUTO_KEY,CODE,COUNTRY_NAME,SDF_COC_002,SDF_COC_003) values (102,'CA','Canada','North America','F');
Insert into COUNTRY_CODES (COC_AUTO_KEY,CODE,COUNTRY_NAME,SDF_COC_002,SDF_COC_003) values (103,'CC','Cocos (Keeling) Islands','Asia','F');
Insert into COUNTRY_CODES (COC_AUTO_KEY,CODE,COUNTRY_NAME,SDF_COC_002,SDF_COC_003) values (104,'CF','Central African Republic','Africa','F');
Insert into COUNTRY_CODES (COC_AUTO_KEY,CODE,COUNTRY_NAME,SDF_COC_002,SDF_COC_003) values (105,'CG','Congo','Africa','F');
Insert into COUNTRY_CODES (COC_AUTO_KEY,CODE,COUNTRY_NAME,SDF_COC_002,SDF_COC_003) values (106,'CH','Switzerland','Europe','F');
Insert into COUNTRY_CODES (COC_AUTO_KEY,CODE,COUNTRY_NAME,SDF_COC_002,SDF_COC_003) values (107,'CK','Cook Islands','Australia/Oceania','F');
Insert into COUNTRY_CODES (COC_AUTO_KEY,CODE,COUNTRY_NAME,SDF_COC_002,SDF_COC_003) values (108,'CL','Chile','South America','F');
Insert into COUNTRY_CODES (COC_AUTO_KEY,CODE,COUNTRY_NAME,SDF_COC_002,SDF_COC_003) values (109,'CM','Cameroon','Africa','F');
Insert into COUNTRY_CODES (COC_AUTO_KEY,CODE,COUNTRY_NAME,SDF_COC_002,SDF_COC_003) values (110,'CN','China','Asia','F');
Insert into COUNTRY_CODES (COC_AUTO_KEY,CODE,COUNTRY_NAME,SDF_COC_002,SDF_COC_003) values (111,'CO','Colombia','South America','F');
Insert into COUNTRY_CODES (COC_AUTO_KEY,CODE,COUNTRY_NAME,SDF_COC_002,SDF_COC_003) values (112,'CR','Costa Rica','Central America','F');
Insert into COUNTRY_CODES (COC_AUTO_KEY,CODE,COUNTRY_NAME,SDF_COC_002,SDF_COC_003) values (113,'CU','Cuba','Central America','F');
Insert into COUNTRY_CODES (COC_AUTO_KEY,CODE,COUNTRY_NAME,SDF_COC_002,SDF_COC_003) values (114,'CV','Cape Verde','Africa','F');
Insert into COUNTRY_CODES (COC_AUTO_KEY,CODE,COUNTRY_NAME,SDF_COC_002,SDF_COC_003) values (115,'CX','Christmas Island','Asia','F');
Insert into COUNTRY_CODES (COC_AUTO_KEY,CODE,COUNTRY_NAME,SDF_COC_002,SDF_COC_003) values (116,'CY','Cyprus','Europe','T');
Insert into COUNTRY_CODES (COC_AUTO_KEY,CODE,COUNTRY_NAME,SDF_COC_002,SDF_COC_003) values (117,'CZ','Czech Republic','Europe','T');
Insert into COUNTRY_CODES (COC_AUTO_KEY,CODE,COUNTRY_NAME,SDF_COC_002,SDF_COC_003) values (121,'DM','Dominica','Central America','F');
Insert into COUNTRY_CODES (COC_AUTO_KEY,CODE,COUNTRY_NAME,SDF_COC_002,SDF_COC_003) values (119,'DJ','Djibouti','Africa','F');
Insert into COUNTRY_CODES (COC_AUTO_KEY,CODE,COUNTRY_NAME,SDF_COC_002,SDF_COC_003) values (120,'DK','Denmark','Europe','T');
Insert into COUNTRY_CODES (COC_AUTO_KEY,CODE,COUNTRY_NAME,SDF_COC_002,SDF_COC_003) values (122,'DO','Dominican Republic','Central America','F');
Insert into COUNTRY_CODES (COC_AUTO_KEY,CODE,COUNTRY_NAME,SDF_COC_002,SDF_COC_003) values (123,'DZ','Algeria','Africa','F');
Insert into COUNTRY_CODES (COC_AUTO_KEY,CODE,COUNTRY_NAME,SDF_COC_002,SDF_COC_003) values (124,'EC','Ecuador','South America','F');
Insert into COUNTRY_CODES (COC_AUTO_KEY,CODE,COUNTRY_NAME,SDF_COC_002,SDF_COC_003) values (125,'EE','Estonia','Europe','T');
Insert into COUNTRY_CODES (COC_AUTO_KEY,CODE,COUNTRY_NAME,SDF_COC_002,SDF_COC_003) values (126,'EG','Egypt','Africa','F');
Insert into COUNTRY_CODES (COC_AUTO_KEY,CODE,COUNTRY_NAME,SDF_COC_002,SDF_COC_003) values (127,'EH','Western Sahara','Africa','F');
Insert into COUNTRY_CODES (COC_AUTO_KEY,CODE,COUNTRY_NAME,SDF_COC_002,SDF_COC_003) values (128,'ER','Eritrea','Africa','F');
Insert into COUNTRY_CODES (COC_AUTO_KEY,CODE,COUNTRY_NAME,SDF_COC_002,SDF_COC_003) values (129,'ES','Spain','Europe','T');
Insert into COUNTRY_CODES (COC_AUTO_KEY,CODE,COUNTRY_NAME,SDF_COC_002,SDF_COC_003) values (130,'ET','Ethiopia','Africa','F');
Insert into COUNTRY_CODES (COC_AUTO_KEY,CODE,COUNTRY_NAME,SDF_COC_002,SDF_COC_003) values (131,'FI','Finland','Europe','T');
Insert into COUNTRY_CODES (COC_AUTO_KEY,CODE,COUNTRY_NAME,SDF_COC_002,SDF_COC_003) values (132,'FJ','Fiji','Australia/Oceania','F');
Insert into COUNTRY_CODES (COC_AUTO_KEY,CODE,COUNTRY_NAME,SDF_COC_002,SDF_COC_003) values (133,'FK','Falkland Islands','South America','F');
Insert into COUNTRY_CODES (COC_AUTO_KEY,CODE,COUNTRY_NAME,SDF_COC_002,SDF_COC_003) values (134,'FM','Micronesia','Australia/Oceania','F');
Insert into COUNTRY_CODES (COC_AUTO_KEY,CODE,COUNTRY_NAME,SDF_COC_002,SDF_COC_003) values (135,'FO','Faroe Islands','Europe','F');
Insert into COUNTRY_CODES (COC_AUTO_KEY,CODE,COUNTRY_NAME,SDF_COC_002,SDF_COC_003) values (136,'FR','France','Europe','T');
Insert into COUNTRY_CODES (COC_AUTO_KEY,CODE,COUNTRY_NAME,SDF_COC_002,SDF_COC_003) values (137,'GA','Gabon','Africa','F');
Insert into COUNTRY_CODES (COC_AUTO_KEY,CODE,COUNTRY_NAME,SDF_COC_002,SDF_COC_003) values (138,'GD','Grenada','Central America','F');
Insert into COUNTRY_CODES (COC_AUTO_KEY,CODE,COUNTRY_NAME,SDF_COC_002,SDF_COC_003) values (139,'GE','Georgia','Asia','F');
Insert into COUNTRY_CODES (COC_AUTO_KEY,CODE,COUNTRY_NAME,SDF_COC_002,SDF_COC_003) values (140,'OM','Oman','Asia','F');
Insert into COUNTRY_CODES (COC_AUTO_KEY,CODE,COUNTRY_NAME,SDF_COC_002,SDF_COC_003) values (141,'NZ','New Zealand','Australia/Oceania','F');
Insert into COUNTRY_CODES (COC_AUTO_KEY,CODE,COUNTRY_NAME,SDF_COC_002,SDF_COC_003) values (142,'NU','Niue','Australia/Oceania','F');
Insert into COUNTRY_CODES (COC_AUTO_KEY,CODE,COUNTRY_NAME,SDF_COC_002,SDF_COC_003) values (143,'NR','Nauru','Australia/Oceania','F');
Insert into COUNTRY_CODES (COC_AUTO_KEY,CODE,COUNTRY_NAME,SDF_COC_002,SDF_COC_003) values (144,'NP','Nepal','Asia','F');
Insert into COUNTRY_CODES (COC_AUTO_KEY,CODE,COUNTRY_NAME,SDF_COC_002,SDF_COC_003) values (145,'NO','Norway','Europe','F');
Insert into COUNTRY_CODES (COC_AUTO_KEY,CODE,COUNTRY_NAME,SDF_COC_002,SDF_COC_003) values (146,'NL','Netherlands','Europe','T');
Insert into COUNTRY_CODES (COC_AUTO_KEY,CODE,COUNTRY_NAME,SDF_COC_002,SDF_COC_003) values (147,'NG','Nigeria','Africa','F');
Insert into COUNTRY_CODES (COC_AUTO_KEY,CODE,COUNTRY_NAME,SDF_COC_002,SDF_COC_003) values (148,'NF','Norfolk Island','Australia/Oceania','F');
Insert into COUNTRY_CODES (COC_AUTO_KEY,CODE,COUNTRY_NAME,SDF_COC_002,SDF_COC_003) values (149,'NE','Niger','Africa','F');
Insert into COUNTRY_CODES (COC_AUTO_KEY,CODE,COUNTRY_NAME,SDF_COC_002,SDF_COC_003) values (150,'NC','New Caledonia (French)','Australia/Oceania','F');
Insert into COUNTRY_CODES (COC_AUTO_KEY,CODE,COUNTRY_NAME,SDF_COC_002,SDF_COC_003) values (151,'NA','Namibia','Africa','F');
Insert into COUNTRY_CODES (COC_AUTO_KEY,CODE,COUNTRY_NAME,SDF_COC_002,SDF_COC_003) values (152,'MZ','Mozambique','Africa','F');
Insert into COUNTRY_CODES (COC_AUTO_KEY,CODE,COUNTRY_NAME,SDF_COC_002,SDF_COC_003) values (153,'MY','Malaysia','Asia','F');
Insert into COUNTRY_CODES (COC_AUTO_KEY,CODE,COUNTRY_NAME,SDF_COC_002,SDF_COC_003) values (154,'MX','Mexico','North America','F');
Insert into COUNTRY_CODES (COC_AUTO_KEY,CODE,COUNTRY_NAME,SDF_COC_002,SDF_COC_003) values (155,'MV','Maldives','Asia','F');
Insert into COUNTRY_CODES (COC_AUTO_KEY,CODE,COUNTRY_NAME,SDF_COC_002,SDF_COC_003) values (156,'MU','Mauritius','Africa','F');
Insert into COUNTRY_CODES (COC_AUTO_KEY,CODE,COUNTRY_NAME,SDF_COC_002,SDF_COC_003) values (157,'MT','Malta','Europe','T');
Insert into COUNTRY_CODES (COC_AUTO_KEY,CODE,COUNTRY_NAME,SDF_COC_002,SDF_COC_003) values (158,'MS','Montserrat','North America','F');
Insert into COUNTRY_CODES (COC_AUTO_KEY,CODE,COUNTRY_NAME,SDF_COC_002,SDF_COC_003) values (159,'MR','Mauritania','Africa','F');
Insert into COUNTRY_CODES (COC_AUTO_KEY,CODE,COUNTRY_NAME,SDF_COC_002,SDF_COC_003) values (160,'MQ','Martinique (French)','North America','F');
Insert into COUNTRY_CODES (COC_AUTO_KEY,CODE,COUNTRY_NAME,SDF_COC_002,SDF_COC_003) values (161,'MP','Northern Mariana Islands','Australia/Oceania','F');
Insert into COUNTRY_CODES (COC_AUTO_KEY,CODE,COUNTRY_NAME,SDF_COC_002,SDF_COC_003) values (162,'MO','Macau','Asia','F');
Insert into COUNTRY_CODES (COC_AUTO_KEY,CODE,COUNTRY_NAME,SDF_COC_002,SDF_COC_003) values (163,'MN','Mongolia','Asia','F');
Insert into COUNTRY_CODES (COC_AUTO_KEY,CODE,COUNTRY_NAME,SDF_COC_002,SDF_COC_003) values (164,'MM','Myanmar','Asia','F');
Insert into COUNTRY_CODES (COC_AUTO_KEY,CODE,COUNTRY_NAME,SDF_COC_002,SDF_COC_003) values (165,'ML','Mali','Africa','F');
Insert into COUNTRY_CODES (COC_AUTO_KEY,CODE,COUNTRY_NAME,SDF_COC_002,SDF_COC_003) values (166,'MK','Macedonia','Europe','F');
Insert into COUNTRY_CODES (COC_AUTO_KEY,CODE,COUNTRY_NAME,SDF_COC_002,SDF_COC_003) values (167,'MH','Marshall Islands','Australia/Oceania','F');
Insert into COUNTRY_CODES (COC_AUTO_KEY,CODE,COUNTRY_NAME,SDF_COC_002,SDF_COC_003) values (168,'MG','Madagascar','Africa','F');
Insert into COUNTRY_CODES (COC_AUTO_KEY,CODE,COUNTRY_NAME,SDF_COC_002,SDF_COC_003) values (169,'MD','Moldova','Europe','F');
Insert into COUNTRY_CODES (COC_AUTO_KEY,CODE,COUNTRY_NAME,SDF_COC_002,SDF_COC_003) values (170,'MC','Monaco','Europe','F');
Insert into COUNTRY_CODES (COC_AUTO_KEY,CODE,COUNTRY_NAME,SDF_COC_002,SDF_COC_003) values (171,'MA','Morocco','Africa','F');
Insert into COUNTRY_CODES (COC_AUTO_KEY,CODE,COUNTRY_NAME,SDF_COC_002,SDF_COC_003) values (172,'LY','Libya','Africa','F');
Insert into COUNTRY_CODES (COC_AUTO_KEY,CODE,COUNTRY_NAME,SDF_COC_002,SDF_COC_003) values (173,'LV','Latvia','Europe','T');
Insert into COUNTRY_CODES (COC_AUTO_KEY,CODE,COUNTRY_NAME,SDF_COC_002,SDF_COC_003) values (174,'LU','Luxembourg','Europe','T');
Insert into COUNTRY_CODES (COC_AUTO_KEY,CODE,COUNTRY_NAME,SDF_COC_002,SDF_COC_003) values (175,'LS','Lesotho','Africa','F');
Insert into COUNTRY_CODES (COC_AUTO_KEY,CODE,COUNTRY_NAME,SDF_COC_002,SDF_COC_003) values (176,'LR','Liberia','Africa','F');
Insert into COUNTRY_CODES (COC_AUTO_KEY,CODE,COUNTRY_NAME,SDF_COC_002,SDF_COC_003) values (177,'LK','Sri Lanka','Asia','F');
Insert into COUNTRY_CODES (COC_AUTO_KEY,CODE,COUNTRY_NAME,SDF_COC_002,SDF_COC_003) values (178,'LI','Liechtenstein','Europe','F');
Insert into COUNTRY_CODES (COC_AUTO_KEY,CODE,COUNTRY_NAME,SDF_COC_002,SDF_COC_003) values (179,'LC','Saint Lucia','Central America','F');
Insert into COUNTRY_CODES (COC_AUTO_KEY,CODE,COUNTRY_NAME,SDF_COC_002,SDF_COC_003) values (180,'LB','Lebanon','Asia','F');
Insert into COUNTRY_CODES (COC_AUTO_KEY,CODE,COUNTRY_NAME,SDF_COC_002,SDF_COC_003) values (181,'LA','Lao People''s Democratic Republic','Asia','F');
Insert into COUNTRY_CODES (COC_AUTO_KEY,CODE,COUNTRY_NAME,SDF_COC_002,SDF_COC_003) values (182,'KZ','Kazakhstan','Asia','F');
Insert into COUNTRY_CODES (COC_AUTO_KEY,CODE,COUNTRY_NAME,SDF_COC_002,SDF_COC_003) values (183,'KY','Cayman Islands','North America','F');
Insert into COUNTRY_CODES (COC_AUTO_KEY,CODE,COUNTRY_NAME,SDF_COC_002,SDF_COC_003) values (184,'KW','Kuwait','Asia','F');
Insert into COUNTRY_CODES (COC_AUTO_KEY,CODE,COUNTRY_NAME,SDF_COC_002,SDF_COC_003) values (185,'KN','Saint Kitts & Nevis Anguilla','Central America','F');
Insert into COUNTRY_CODES (COC_AUTO_KEY,CODE,COUNTRY_NAME,SDF_COC_002,SDF_COC_003) values (186,'KM','Comoros','Africa','F');
Insert into COUNTRY_CODES (COC_AUTO_KEY,CODE,COUNTRY_NAME,SDF_COC_002,SDF_COC_003) values (187,'KI','Kiribati','Australia/Oceania','F');
Insert into COUNTRY_CODES (COC_AUTO_KEY,CODE,COUNTRY_NAME,SDF_COC_002,SDF_COC_003) values (188,'KH','Cambodia','Asia','F');
Insert into COUNTRY_CODES (COC_AUTO_KEY,CODE,COUNTRY_NAME,SDF_COC_002,SDF_COC_003) values (189,'KG','Kyrgyzstan','Asia','F');
Insert into COUNTRY_CODES (COC_AUTO_KEY,CODE,COUNTRY_NAME,SDF_COC_002,SDF_COC_003) values (190,'KE','Kenya','Africa','F');
Insert into COUNTRY_CODES (COC_AUTO_KEY,CODE,COUNTRY_NAME,SDF_COC_002,SDF_COC_003) values (191,'JP','Japan','Asia','F');
Insert into COUNTRY_CODES (COC_AUTO_KEY,CODE,COUNTRY_NAME,SDF_COC_002,SDF_COC_003) values (192,'JO','Jordan','Asia','F');
Insert into COUNTRY_CODES (COC_AUTO_KEY,CODE,COUNTRY_NAME,SDF_COC_002,SDF_COC_003) values (193,'JM','Jamaica','Central America','F');
Insert into COUNTRY_CODES (COC_AUTO_KEY,CODE,COUNTRY_NAME,SDF_COC_002,SDF_COC_003) values (194,'IT','Italy','Europe','T');
Insert into COUNTRY_CODES (COC_AUTO_KEY,CODE,COUNTRY_NAME,SDF_COC_002,SDF_COC_003) values (195,'IS','Iceland','Europe','F');
Insert into COUNTRY_CODES (COC_AUTO_KEY,CODE,COUNTRY_NAME,SDF_COC_002,SDF_COC_003) values (196,'IR','Iran','Asia','F');
Insert into COUNTRY_CODES (COC_AUTO_KEY,CODE,COUNTRY_NAME,SDF_COC_002,SDF_COC_003) values (197,'IQ','Iraq','Asia','F');
Insert into COUNTRY_CODES (COC_AUTO_KEY,CODE,COUNTRY_NAME,SDF_COC_002,SDF_COC_003) values (198,'IO','British Indian Ocean Territory','Asia','F');
Insert into COUNTRY_CODES (COC_AUTO_KEY,CODE,COUNTRY_NAME,SDF_COC_002,SDF_COC_003) values (199,'INT','International',null,null);
Insert into COUNTRY_CODES (COC_AUTO_KEY,CODE,COUNTRY_NAME,SDF_COC_002,SDF_COC_003) values (200,'IN','India','Asia','F');
Insert into COUNTRY_CODES (COC_AUTO_KEY,CODE,COUNTRY_NAME,SDF_COC_002,SDF_COC_003) values (201,'IL','Israel','Asia','F');
Insert into COUNTRY_CODES (COC_AUTO_KEY,CODE,COUNTRY_NAME,SDF_COC_002,SDF_COC_003) values (202,'IE','Ireland','Europe','T');
Insert into COUNTRY_CODES (COC_AUTO_KEY,CODE,COUNTRY_NAME,SDF_COC_002,SDF_COC_003) values (203,'ID','Indonesia','Asia','F');
Insert into COUNTRY_CODES (COC_AUTO_KEY,CODE,COUNTRY_NAME,SDF_COC_002,SDF_COC_003) values (204,'HU','Hungary','Europe','T');
Insert into COUNTRY_CODES (COC_AUTO_KEY,CODE,COUNTRY_NAME,SDF_COC_002,SDF_COC_003) values (205,'HT','Haiti','Central America','F');
Insert into COUNTRY_CODES (COC_AUTO_KEY,CODE,COUNTRY_NAME,SDF_COC_002,SDF_COC_003) values (206,'HR','Croatia','Europe','T');
Insert into COUNTRY_CODES (COC_AUTO_KEY,CODE,COUNTRY_NAME,SDF_COC_002,SDF_COC_003) values (207,'HN','Honduras','Central America','F');
Insert into COUNTRY_CODES (COC_AUTO_KEY,CODE,COUNTRY_NAME,SDF_COC_002,SDF_COC_003) values (208,'HM','Heard and McDonald Islands','Antarctica','F');
Insert into COUNTRY_CODES (COC_AUTO_KEY,CODE,COUNTRY_NAME,SDF_COC_002,SDF_COC_003) values (209,'HK','Hong Kong','Asia','F');
Insert into COUNTRY_CODES (COC_AUTO_KEY,CODE,COUNTRY_NAME,SDF_COC_002,SDF_COC_003) values (210,'GY','Guyana','South America','F');
Insert into COUNTRY_CODES (COC_AUTO_KEY,CODE,COUNTRY_NAME,SDF_COC_002,SDF_COC_003) values (211,'GW','Guinea Bissau','Africa','F');
Insert into COUNTRY_CODES (COC_AUTO_KEY,CODE,COUNTRY_NAME,SDF_COC_002,SDF_COC_003) values (212,'GU','Guam (USA)','Australia/Oceania','F');
Insert into COUNTRY_CODES (COC_AUTO_KEY,CODE,COUNTRY_NAME,SDF_COC_002,SDF_COC_003) values (213,'GT','Guatemala','Central America','F');
Insert into COUNTRY_CODES (COC_AUTO_KEY,CODE,COUNTRY_NAME,SDF_COC_002,SDF_COC_003) values (214,'GR','Greece','Europe','T');
Insert into COUNTRY_CODES (COC_AUTO_KEY,CODE,COUNTRY_NAME,SDF_COC_002,SDF_COC_003) values (215,'GQ','Equatorial Guinea','Africa','F');
Insert into COUNTRY_CODES (COC_AUTO_KEY,CODE,COUNTRY_NAME,SDF_COC_002,SDF_COC_003) values (216,'GP','Guadeloupe (French)','North America','F');
Insert into COUNTRY_CODES (COC_AUTO_KEY,CODE,COUNTRY_NAME,SDF_COC_002,SDF_COC_003) values (217,'GN','Guinea','Africa','F');
Insert into COUNTRY_CODES (COC_AUTO_KEY,CODE,COUNTRY_NAME,SDF_COC_002,SDF_COC_003) values (218,'GM','Gambia','Africa','F');
Insert into COUNTRY_CODES (COC_AUTO_KEY,CODE,COUNTRY_NAME,SDF_COC_002,SDF_COC_003) values (219,'GL','Greenland','North America','F');
Insert into COUNTRY_CODES (COC_AUTO_KEY,CODE,COUNTRY_NAME,SDF_COC_002,SDF_COC_003) values (220,'GI','Gibraltar','Europe','F');
Insert into COUNTRY_CODES (COC_AUTO_KEY,CODE,COUNTRY_NAME,SDF_COC_002,SDF_COC_003) values (221,'GH','Ghana','Africa','F');
Insert into COUNTRY_CODES (COC_AUTO_KEY,CODE,COUNTRY_NAME,SDF_COC_002,SDF_COC_003) values (222,'GF','French Guyana','South America','F');
Insert into COUNTRY_CODES (COC_AUTO_KEY,CODE,COUNTRY_NAME,SDF_COC_002,SDF_COC_003) values (231,'BM','Bermuda','North America','F');
Insert into COUNTRY_CODES (COC_AUTO_KEY,CODE,COUNTRY_NAME,SDF_COC_002,SDF_COC_003) values (233,'SD','Sudan','Africa','F');
Insert into COUNTRY_CODES (COC_AUTO_KEY,CODE,COUNTRY_NAME,SDF_COC_002,SDF_COC_003) values (234,'ME','Montenegro','Europe','F');
Insert into COUNTRY_CODES (COC_AUTO_KEY,CODE,COUNTRY_NAME,SDF_COC_002,SDF_COC_003) values (225,'BA','Bosnia and Herzegovina','Europe','F');
Insert into COUNTRY_CODES (COC_AUTO_KEY,CODE,COUNTRY_NAME,SDF_COC_002,SDF_COC_003) values (246,'SS','South Sudan','Africa','F');
Insert into COUNTRY_CODES (COC_AUTO_KEY,CODE,COUNTRY_NAME,SDF_COC_002,SDF_COC_003) values (247,'AO','Angola','Africa','F');
Insert into COUNTRY_CODES (COC_AUTO_KEY,CODE,COUNTRY_NAME,SDF_COC_002,SDF_COC_003) values (255,'CI','Cote d''Ivoire','Africa','F');
Insert into COUNTRY_CODES (COC_AUTO_KEY,CODE,COUNTRY_NAME,SDF_COC_002,SDF_COC_003) values (244,'SV','El Salvador','Central America','F');
Insert into COUNTRY_CODES (COC_AUTO_KEY,CODE,COUNTRY_NAME,SDF_COC_002,SDF_COC_003) values (245,'BO','Bolivia','South America','F');
Insert into COUNTRY_CODES (COC_AUTO_KEY,CODE,COUNTRY_NAME,SDF_COC_002,SDF_COC_003) values (256,'PY','Paraguay','South America','F');
